/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package odevPart2;

import java.util.ArrayList;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.Arrays;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    public void testFound(){
        ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1,2,3,4));
        assertTrue(App.search(array, 2, 2));
    } 

    @Test
    public void testFound2(){
        ArrayList<Integer> array = new ArrayList<>(Arrays.asList(10,30,50,100));
        assertTrue(App.search(array, 25, 2));
    }

    @Test
    public void testNotFound(){
        ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1,2,3,4));
        assertFalse(App.search(array, 1, 5));
    } 

    @Test
    public void testNotFound2(){
        ArrayList<Integer> array = new ArrayList<>(Arrays.asList(10,100,200,40));
        assertFalse(App.search(array, 10, 5));
    } 

    @Test
    public void testEmptyArray(){
        ArrayList<Integer> array = new ArrayList<>();
        assertFalse(App.search(array, 1, 2));;
    }

    @Test
    public void testNull(){
        assertFalse(App.search(null, 1, 2));
    }


}
